# Subclonal dynamics

```{r libraries and sources for subclonal dynamics analysis, echo = T, message=FALSE, warning=FALSE}
# Libraries and sources
library(tidyverse)
library(AneuFinder)
library(GenomeInfoDb)
library(BSgenome.Hsapiens.UCSC.hg38)
library(stringr)
source('R/plot_pca_kmeans.R')
source('R/quality_functions.R')
source('R/quality_functions.R')
```

## AneuFinder Run
```{r running aneufinder (NOT RUN), eval=FALSE}
###########
# Folders #
###########
# define bamdirectory
bamDirectory <- "../cna_analysis/data/subclonal_dynamics/single_cell_bams"

# generates novel directories from bam-file directory to store analysis files
inputdirs <- list.dirs(bamDirectory, recursive = F)
outputdirs <- list.dirs(bamDirectory, full.names = F, recursive = F)
outputdirs <-
  paste0("rda/subclonal_dynamics/standard_aneufinder_output_pairedend_5kb/", outputdirs)

# define location for correction:
mappability <-
  "data/subclonal_dynamics/correctionfiles/bothlymphsdiploidref.bed"
blacklist <-
  "data/subclonal_dynamics/correctionfiles/GRCh38_blacklist_bothlymphsdiploidref.bed"

# creating a results folder in the working directory names 'result'
dir.create(path = 'rda/subclonal_dynamics/standard_aneufinder_output_pairedend_5kb')

# creating folders for each plate in the standard_aneufinder_output folder.
for (i in 1:length(outputdirs)) {
  dir.create(path =  outputdirs[i])
}

#######
# Run #
#######
# iterates through bam-file directories and analyses results
for (i in 4:length(inputdirs)) {
  BamFolder <- paste0(inputdirs[i], '/split_cells')
  Aneufinder(
    # specifying input and outputfolder
    inputfolder = BamFolder,
    outputfolder = outputdirs[i],
    
    # general settings
    numCPU  =  10,
    reuse.existing.files  =  TRUE,
    
    # specifying binning options
    binsizes  =  5e+05, # 500000
    stepsizes = 5e+05,
    variable.width.reference = mappability,
    reads.per.bin  =  NULL,
    pairedEndReads  =  T,
    assembly = 'hg38',
    chromosomes  =  c(
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      '14',
      '15',
      '16',
      '17',
      '18',
      '19',
      '20',
      '21',
      '22',
      'X'
    ),
    remove.duplicate.reads  =  F,
    min.mapq  =  10,
    blacklist = blacklist,
    reads.store = T,
    use.bamsignals = F,
    
    # specifying correction options
    correction.method = 'GC',
    GC.BSgenome  =  BSgenome.Hsapiens.UCSC.hg38,
    #mappability.reference = NULL,
    
    #specofying model options
    method  =  c('edivisive'),
    eps = 0.1,
    max.time = 60,
    max.iter = -1,
    num.trials = 15,
    
    states  =  c(
      'zero-inflation',
      '0-somy',
      '1-somy',
      '2-somy',
      '3-somy',
      '4-somy',
      '5-somy',
      '6-somy',
      '7-somy',
      '8-somy',
      '9-somy',
      '+10-somy'
    ),
    #most.frequent.state  =  '2-somy', # maybe this should be changed given some organoids seem triploid.
    #most.frequent.state.strandseq  =  '1-somy',
    
    #specifying how to detect sister chromatid exchanges
    #resolution = c(3,6),
    #min.segwidth  =  4,
    #bw  =  4e+06,
    #pval  =  0.05,
    
    # plotting options
    cluster.plots = T
  )
}
```


## Quality selection
```{r quality run (NOT RUN), eval = FALSE}
###############
# Description #
###############
# Single cell karyotyping is inherently noisy data. This script runs
# some of the in-build quality checks provided by AneuFinder

#########
# Paths #
#########
#  defining rdabasedirectory
rdaBaseDirectory <-
  "../cna_analysis/rda/subclonal_dynamics/standard_aneufinder_output_pairedend_5kb"

# list all folders within base directory (each folder contains folders the AneuFinder output: MODELS, plots etc..)
# the files we need are in the MODELS folder
inputdirs <- list.dirs(rdaBaseDirectory, recursive = F)

# define the model we want to use (this can be 'dnacopy, edivisive, or HMM')
model = 'edivisive'

modeldirs <- list.dirs(rdaBaseDirectory, recursive = F)

#######
# Run #
#######
# run for edivisive
cl_list_edivisive <- list()

for (i in 1:(length(inputdirs))) {
  # function
  cl_list_edivisive[[paste0('kra', str_extract(pattern = '\\d{3}', inputdirs[i]))]] <-
    quality_check(inputdir = inputdirs[i], model = 'edivisive')
  
}

########
# Save #
########
save(cl_list_edivisive, file = '../cna_analysis/rda/subclonal_dynamics/cl_list_edivisive_paired.rda')

```

```{r quality select (NOT RUN), eval = F, echo = T, message=FALSE, warning=FALSE}
########
# Data #
########
load('../cna_analysis/rda/subclonal_dynamics/cl_list_edivisive_paired.rda')

#################
# Quality check #
#################
qual_summary <- lapply(cl_list_edivisive, check_quality)

#######
# Run #
#######
select_files_edivisive <-
  lapply(cl_list_edivisive,
         quality_select,
         spik = 0.7,
         bhat = 0)

########
# Save #
########
save(select_files_edivisive, file = '../cna_analysis/rda/subclonal_dynamics/select_files_edivisive.rda')

```

```{r manual removal, eval = F, echo = T, message=FALSE, warning=FALSE}
###############
# Description #
###############
# After AneuFinder's inbuild quaility selection, there are still some evident 
# noisy single cells, that appear on the heatmap as if having very high and 
# unstructured ploidy. These single cell's will be removed manually here. The cells
# were selected by inspecting standard AneuFinder heatmaps on the post-quality
# selected files (code not shown).
########
# Data #
########
# loading files after quality selection
load('../cna_analysis/rda/subclonal_dynamics/select_files_edivisive.rda')

##########
# Select #
##########
# removing karyotypes that are clearly artefacts. The karyotypes are 
# selected based on the figures in figs -> genomeheatmap_afterqc -> edivisive
kra003_remove <- as.character(c( 272, 122  , 33  ,  198  ,  
                                 372,  116  ,  105 , 104,  175  , 
                                 341  , 30, 12  ,  280  , 215  , 
                                 31  ,  139  ,  295 ,  370  ,  337  ,  
                                 307  , 170  ,80  ,  357 , 34, 21  , 60  ,  
                                 129  , 318  , 39 ,  365, 
                                 113  ,  89  , 4  ,  57 , 162  ,  20  , 
                                 135  , 235  , 377  , 181 , 46  , 84  , 
                                 186  , 81,  257  , 225  , 191  , 269))
  
kra004_remove <- as.character(c(266, 251, 375, 256, 303, 179, 160, 290, 368, 28, 334, 211, 261, 58, 133, 115, 161, 20, 162, 112, 314, 181, 264, 268, 268, 30, 127, 98, 191, 383,
                                232, 104, 350, 163, 377, 323, 333, 224, 242, 184, 244, 277, 102, 21, 93, 149, 101, 332, 188, 225, 135))
                                


kra005_remove <- as.character(c(89, 159, 61, 155, 146, 141, 30, 174, 95, 262, 264,
                                48, 152, 103, 92, 116,
                                297, 333))




kra006_remove <- as.character(c(380, 176, 328, 255, 4,
                                60, 264, 111, 173))




kra007_remove <- as.character(c(37, 366, 213, 262, 83, 78, 10, 
                                351))
                                
                                ## diploid subclone91, 363, 275))


kra008_remove <- as.character(c(70, 143, 77, 144, 146, 189, 
                                35, 170, 30, 119, 65, 51, 107, 
                                362, 58 ,125, 66 ,210 ,160 ,186, 
                                102, 37, 226, 183, 59, 159, 46, 87, 
                                118, 285, 69, 109))
                                
                                
                                # diploid subclone
                                # 287, 302, 212, 15, 
                                # 115, 166, 126, 17, 95, 231, 19, 104, 
                                # 86, 138, 105, 116, 81 ,130, 88, 61)) 

kra009_remove <- as.character(c(239, 347, 94, 65, 91, 
                                163, 246, 6 ,116, 330, 126, 76, 54, 
                                57, 107 ,181, 154, 137, 60, 114, 55, 
                                81, 179, 241, 75, 142,
                                329, 323))


# diploid subclone kra009 74, 59, 375, 112, 92, 99, 
# 105

kra010_remove <- as.character(c(363, 217, 242, 238, 27, 46, 189, 28,
                                   216, 84, 234, 71, 95, 60, 86, 181, 172,
                                   42, 355, 58, 43, 132,
                                   262, 176, 143,311, 203, 297,307, 3, 227,
                                   72,
                                   177, 115, 54, 258))

kra022_remove <- as.character(c(5, 31, 161))

# kra003_subclone<- as.character(c(372, 173, 274, 108, 39, 289)) 


kra023_remove <- as.character(c(96, 199, 246, 135, 
                                104,
                                5))

# kra004_subclone<- as.character(c(92, 102, 252, 181,
#                                 264, 258, 290, 268) 



kra024_remove <- as.character(c(193, 344, 337, 356, 
                                85,86,309,52,
                                188,374, 176,53,
                                87,169,36,115,
                                45,281,66))

# kra005_subclone <- as.character(c(297, 92, 113, 103, 
#                                   152, 48, 333))


kra025_remove <- as.character(c(141, 257,85,183,127))

# kra006_subclone <- as.character(c(380))


kra026_remove <- as.character(c(318, 287, 260, 208, 
                                247, 75, 285,
                                376, 238, 200, 215, 362, 49))

# kra007_subclone <- as.character(c(318, 292, 381, 319, 
#                                   198, 208, 351, 353, 
#                                   285, 379))

kra027_remove <- as.character(c(339, 375, 141, 
                                126, 346, 204, 
                                69, 343, 377, 
                                364, 298, 79))

# kra008_subclone <- as.character(c(69, 87, 60, 61, 
#                                   143, 35, 241, 202))


kra028_remove <- as.character(c(37, 178, 167, 225, 125, 
                                90, 249, 50,66, 327 ))

# kra009_subclone1 <- as.character(c(375))



kra029_remove <- as.character(c(14, 277, 353, 203,
                                137
))


kra030_remove <- as.character(c(341,
                                177, 111, 157, 226, 
                                209, 150, 301, 158,
                                121, 273, 190, 47, 18
))

kra031_remove <- as.character(c(159, 217, 261, 122, 
                                60, 201, 153))


kra032_remove <- as.character(c(349, 347, 58, 370, 
                                284, 366, 326, 373, 
                                306, 27, 
                                138, 113, 348, 22, 
                                24, 103, 218, 181))



# kra010 has three subclones!!
# kra010_subclone1 <- as.character(c(355,34,166,139,
# 19, 213, 357, 57,
# 72))

# kra010_subclone2 <- 317 t/m 304
# kra010_subclone2 < 235 t/m  176

##########
# Remove #
##########

kra003 <- remove_selection(select_files_edivisive$kra003, kra003_remove)
kra004 <- remove_selection(select_files_edivisive$kra004, kra004_remove)

kra005 <- remove_selection(select_files_edivisive$kra005, kra005_remove)
kra006 <- remove_selection(select_files_edivisive$kra006, kra006_remove)

kra007 <- remove_selection(select_files_edivisive$kra007, kra007_remove)
kra008 <- remove_selection(select_files_edivisive$kra008, kra008_remove)

kra009 <- remove_selection(select_files_edivisive$kra009, kra009_remove)
kra010 <- remove_selection(select_files_edivisive$kra010, kra010_remove)

kra022 <- remove_selection(select_files_edivisive$kra022, kra022_remove)
kra023 <- remove_selection(select_files_edivisive$kra023, kra023_remove)

kra024 <- remove_selection(select_files_edivisive$kra024, kra024_remove)
kra025 <- remove_selection(select_files_edivisive$kra025, kra025_remove)

kra026 <- remove_selection(select_files_edivisive$kra026, kra026_remove)
kra027 <- remove_selection(select_files_edivisive$kra027, kra027_remove)
kra028 <- remove_selection(select_files_edivisive$kra028, kra028_remove)
kra029 <- remove_selection(select_files_edivisive$kra029, kra029_remove)
kra030 <- remove_selection(select_files_edivisive$kra030, kra030_remove)

kra031 <- remove_selection(select_files_edivisive$kra031, kra031_remove)
kra032 <- remove_selection(select_files_edivisive$kra032, kra032_remove)


man_select_files_edivisive <- list(kra003 = kra003,
                                  kra004 = kra004,
                                  
                                  kra005 = kra005,
                                  kra006 = kra006,
                                  
                                  kra007 = kra007,
                                  kra008 = kra008,
                                  
                                  kra009 = kra009,
                                  kra010 = kra010,
                                  
                                  kra022 = kra022,
                                  kra023 = kra023,
                                  
                                  kra024 = kra024,
                                  kra025 = kra025,
                                  
                                  kra026 = kra026,
                                  kra027 = kra027,
                                  kra028 = kra028,
                                  
                                  kra029 = kra029,
                                  kra030 = kra030,
                                  kra031 = kra031,
                                  kra032 = kra032
)

########
# Save #
########

save(man_select_files_edivisive, file = '../cna_analysis/rda/subclonal_dynamics/man_select_files_edivisive.rda' )

```

## Summary statistics of copy number alterations

```{r summary_statistics, echo = T, message=FALSE, warning=FALSE}
########
# Data #
########
load('../cna_analysis/rda/subclonal_dynamics/man_select_files_edivisive.rda' )

###########
# Wrangle #
###########
# removing HUB181I kra024 en kra025
man_select_files_edivisive <- man_select_files_edivisive[!names(man_select_files_edivisive) %in% c('kra024', 'kra025')]

# !!! GITHUB SPECIFIC CODE !!! #
# adding '../cna_analysis/' to each path within man_select_files_edivisive 
man_select_files_edivisive <- lapply(man_select_files_edivisive, function(x) paste0("../cna_analysis/", x))

#######
# Run #
#######
# loading segment data from files
files_loaded <- loadFromFiles(unlist(man_select_files_edivisive), check.class=c('GRanges', 'GRangesList', 'aneuHMM', 'aneuBiHMM'))

# Computing the total number of cells sequenced
length(files_loaded)
# computing the total sum of unique CNAs per single cell and store in a vector
cna_vector <- sapply(files_loaded, function(file) {
  seg_grange <- file$segments
  cnas_grange <- seg_grange[seg_grange$copy.number != 2,]
  return(length(cnas_grange))
})

# Computing the mean CNA per single cell
mean(cna_vector)

# Computing the standard deviation of CNAs per single cell.
sd(cna_vector)

```

## PCA and K-means plots
```{r PCA and k-means plots, echo = T, message=FALSE, warning=FALSE}

########
# Plot #
########

# HUB183 #
######################################################################

# PCA #
hub183_pca <- draw_pca(
  man_select_files_edivisive$kra003,
  man_select_files_edivisive$kra004,
  size = 1,
  legend_position = c(0.65, 0.8)
)


hub183_pca

# K-means #
hub183_kmeans <- k_cluster(
  man_select_files_edivisive$kra003,
  man_select_files_edivisive$kra004,
  cluster = 1,
  cols = c("#C6CDF7"),
  labels = c('A'),
  legend_position = c(0.8, 0.85),
  normalize = T,
  return_elbow = F
)
hub183_kmeans

# HUB005 #
######################################################################

# PCA #
hub005_pca <- draw_pca(
  man_select_files_edivisive$kra005,
  man_select_files_edivisive$kra006,
  size = 1,
  legend_position = c(0.65, 0.85)
)

hub005_pca

# K-means #
hub005_kmeans <- k_cluster(
  man_select_files_edivisive$kra005,
  man_select_files_edivisive$kra006,
  cluster = 3,
  cols = c('#809aa6', # greyblue
                    "#D69C4E", # brown,
                    "#046C9A"),
                    #darkblue

  labels = c('A.b', 'B', 'A.a'),
  legend_position = c(0.8, 0.85),
  normalize = T,
  return_elbow = F
)

hub005_kmeans


# HUB106 #
######################################################################

# PCA #
hub106_pca <- draw_pca(
  man_select_files_edivisive$kra007,
  man_select_files_edivisive$kra008,
  size = 1,
  legend_position = c(0.65, 0.95)
)
hub106_pca

# K-means #
hub106_kmeans <- k_cluster(
  man_select_files_edivisive$kra007,
  man_select_files_edivisive$kra008,
  cluster = 3,
  cols = c("#E6A0C4", # pink
                    "#D8A499", #brownpink
                    "#7294D4"),
                    # blue

  labels = c('A', 'C', 'B'),
  legend_position = c(0.8, 0.85),
  normalize = T,
  return_elbow = F
)


hub106_kmeans

# HUB062 #
######################################################################
### Biological replicate 1 ###

# PCA #
hub062_pca_double <-
  draw_pca_double(
    man_select_files_edivisive$kra009,
    man_select_files_edivisive$kra010,
    man_select_files_edivisive$kra030,
    size = 1,
    legend_position = c(0.05, 0.2)
  )


hub062_pca_double

# 'zoom'
hub062_pca_double_zoom <-
  draw_pca_double(
    man_select_files_edivisive$kra009,
    man_select_files_edivisive$kra010,
    man_select_files_edivisive$kra030,
    size = 15,
    legend_position = c(-0.05, 0.25)
  )  +
  coord_cartesian(xlim = c(-0.016, 0.030),
                  ylim = c(0, 0.06)) +
  theme(
    axis.line = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.position = "none",
    panel.background = element_blank(),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.background = element_blank()
  )

hub062_pca_double_zoom

# K-means #
hub062_kmeans_double <-
  k_cluster_double(
    man_select_files_edivisive$kra009,
    man_select_files_edivisive$kra010,
    man_select_files_edivisive$kra030,
    cluster = 3,
    cols = c("#F1BB7B", #orange like
                      "#FD6467", # pinkish red
                      "#5B1A18"),
                      #brownish

    labels = c('C', 'A', 'B'),
    legend_position = c(0.05, 0.2),
    normalize = T,
    return_elbow = F
  )

hub062_kmeans_double

### Biological replicate 2 ###
# PCA #
hub062_pca_rep2 <- draw_pca(
  man_select_files_edivisive$kra028,
  man_select_files_edivisive$kra032,
  size = 1,
  legend_position = c(0.05, 0.9)
)
hub062_pca_rep2

# K-means #
hub062_kmeans_rep2 <- k_cluster(
  man_select_files_edivisive$kra028,
  man_select_files_edivisive$kra032,
  cluster = 3,
  cols = c("#FD6467", # pinkish red
                    "#5B1A18", #brownish
                    "#F1BB7B"),
                    #orange like
  labels = c('A', 'B', 'C'),
  legend_position = c(0.05, 0.9),
  normalize = T
)

hub062_kmeans_rep2

# HUB015 #
######################################################################

# PCA #
hub015_pca <-
  draw_pca(
    man_select_files_edivisive$kra022,
    # 10 gy radiated
    man_select_files_edivisive$kra023,
    # 0 gy control
    size = 1,
    legend_position = c(0.05, 0.8),
    ssdna004 = T
  ) # coordinates do not correspond with coordinates in pc1 and pc2!

hub015_pca

# K-means #
hub015_kmeans <- k_cluster(
  man_select_files_edivisive$kra022,
  man_select_files_edivisive$kra023,
  cluster = 3,
  cols = c("#f5de90",
                    '#E1AF00',

                    '#F21A00'),
                    # red
  labels = c( 'A.a','A.b', 'B'),
  legend_position = c(0.05, 0.8),
  normalize = T,
  return_elbow = F
)

hub015_kmeans

# HUB197 #
######################################################################

# PCA #
hub197_pca <- draw_pca(
  man_select_files_edivisive$kra026,
  # 10 gy
  man_select_files_edivisive$kra027,
  # 0 gy
  # 0 Gy
  size = 1,
  legend_position = c(0.7, 0.8),
  ssdna004 = T
)
hub197_pca

# K-means #
hub197_kmeans <- k_cluster(
  man_select_files_edivisive$kra026,
  man_select_files_edivisive$kra027,
  cluster = 3,
  cols = c("#0B775E",
                    '#E1BD6D',
                    '#35274A'
                    ),

  labels = c('C', 'B', 'A'),
  legend_position = c(0.7, 0.8),
  normalize = T
)

hub197_kmeans

#######
# END #
#######

```